#%RAML 1.0
title: Member REST API
version: v1
baseUri: https://member.api.ftbl.com/
mediaType: application/json

securitySchemes:
  basic:
    type: Basic Authentication

types:
  Member: 
    description: Minimum properties currently supported - type and other information to be added
    type: object
    properties:  
      email: 
        required: true
        type: string
      name:
        type: string

  Account: 
    description: Supply a network and a token/secret and the account will be created by populating the data from the social network
    type: object
    properties:
      network:
        description: facebook and twitter are supported
        required: true
        type: string
      token:
        required: true
        type: string
      secret:
        description: required for twitter
        type: string
      networkId: 
        description: populated from social network
        type: string
      link: 
        description: populated from social network
        type: string

/members:
  post:
    responses:
      200:
        body:
          member:
            type: Member

  get:
    queryParameters:

  /{id}:
    uriParameters:
      id:
        type: string

    get:
      responses:
        200:
          body:
            members:
              type: Member[]

    put:
      responses:
        200:

    delete:
      responses:
        200:

    /accounts:

      post:
        responses:
          200:
            body:
              account:
                type: Account

      get:
        responses:
          200:
            body:
              accounts:
                type: Account[]

    /friends:

    /followers:

    /followeds: